import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
const dom = new JSDOM('<html><body></body></html>', {url:'http://localhost',pretendToBeVisual:true});
for (const key of ['window','document','navigator','HTMLElement','Node','Element','MutationObserver','getComputedStyle','requestAnimationFrame']) Object.defineProperty(globalThis,key,{configurable:true,value:typeof dom.window[key] === 'function' && ['getComputedStyle','requestAnimationFrame'].includes(key) ? dom.window[key].bind(dom.window) : dom.window[key]});
Object.defineProperty(globalThis,'BroadcastChannel',{configurable:true,value:undefined});
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
const {render,screen,cleanup,within} = await import('@testing-library/react');
const user = (await import('@testing-library/user-event')).default.setup();
const {default:DeskPalette} = await import('../src/components/collection/DeskPalette');
const service = await import('../src/services/dataService');
const inks = ['Copper','Green','Blue'].map((name,i)=>({id:String(i),brand:'Maker',collection:'Series',name,colorHex:'#556677'}));
let persisted = [];
let fail = false;
let writes = 0;
globalThis.fetch = async (input,init) => {
    if(String(input).includes('save_desk_palette')) {
        writes++;
        if(fail) return Response.json({code:'offline'},{status:503});
        persisted = JSON.parse(String(init?.body)).p_items;
        return Response.json({items:persisted});
    }
    return Response.json({pens:[],inks:[],events:[],palette:persisted,canEdit:true,asOf:'2026-10-03'});
};
test('owner repeatedly reorders, omits, restores, cancels, saves and retains failed drafts; public is read-only', async () => {
    service.activateCollection('synthetic-owner'); await service.loadData(true);
    const props = {inks,saved:[],canEdit:true,selectedInk:'',onSelect:()=>{},refills:new Map()};
    const ui=render(<DeskPalette {...props}/>);
    await user.click(screen.getByRole('button',{name:'Arrange palette'}));
    const order=()=>within(screen.getByRole('list',{name:'Palette order'})).getAllByRole('listitem').map(el=>el.querySelector('strong')?.textContent);
    await user.click(screen.getByRole('button',{name:'Move Maker Copper later'}));
    assert.deepEqual(order(),['Green','Copper','Blue']);
    await user.click(screen.getByRole('button',{name:'Move Maker Copper later'}));
    await user.click(screen.getByRole('button',{name:'Move Maker Copper earlier'}));
    await user.click(screen.getByRole('button',{name:'Omit Maker Copper'}));
    assert.deepEqual(order(),['Green','Blue']);
    await user.click(screen.getByRole('button',{name:'Restore Copper'}));
    assert.deepEqual(order(),['Green','Copper','Blue']);
    await user.click(screen.getByRole('button',{name:'Cancel'}));
    assert.equal(writes,0);
    await user.click(screen.getByRole('button',{name:'Arrange palette'}));
    for(const ink of inks) await user.click(screen.getByRole('button',{name:`Omit Maker ${ink.name}`}));
    assert.ok(screen.getByText(/Every current color is omitted/));
    await user.click(screen.getByRole('button',{name:'Restore Blue'}));
    fail=true;
    await user.click(screen.getByRole('button',{name:'Save palette'}));
    assert.ok(await screen.findByRole('alert'));
    assert.deepEqual(order(),['Blue']);
    fail=false;
    await user.click(screen.getByRole('button',{name:'Save palette'}));
    await screen.findByRole('button',{name:'Arrange palette'});
    assert.deepEqual(persisted,[{inkId:'0',omitted:true},{inkId:'1',omitted:true},{inkId:'2',omitted:false}]);
    ui.rerender(<DeskPalette {...props} saved={persisted} canEdit={false}/>);
    assert.equal(screen.queryByRole('button',{name:'Arrange palette'}),null);
    assert.ok(screen.getByRole('button',{name:'Filter to Maker Blue'}));
    assert.equal(screen.queryByRole('button',{name:'Restore Copper'}),null);
    assert.equal(writes,2);
    cleanup();
});
