-- Local review candidate. No owner, Auth user, Storage bucket, or production data is provisioned.
create schema private;
revoke all on schema private from public, anon, authenticated;
revoke create on schema public from public, anon, authenticated;
create role collection_writer nologin nosuperuser nocreatedb nocreaterole noinherit nobypassrls;
grant usage on schema public, private, auth to collection_writer;
grant execute on function auth.uid() to collection_writer;
alter default privileges in schema public revoke execute on functions from public;
alter default privileges in schema private revoke execute on functions from public;

create table private.collection_owner (
 singleton boolean primary key default true check (singleton),
 user_id uuid not null unique references auth.users(id) on delete restrict,
 time_zone text not null check (time_zone = 'America/Chicago')
);
create table private.data_imports (
 id text primary key check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id),
 source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
 mapping_version text not null,
 manifest jsonb not null check (jsonb_typeof(manifest) = 'object'),
 imported_at timestamptz not null default now()
);
create table private.mutation_receipts (
 owner_id uuid not null references private.collection_owner(user_id),
 request_id uuid not null,
 command text not null,
 payload_sha256 text not null check (payload_sha256 ~ '^[0-9a-f]{64}$'),
 result jsonb not null check (jsonb_typeof(result) = 'object'),
 created_at timestamptz not null default now(),
 primary key (owner_id, request_id)
);
create table public.pens (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 brand text not null, model text not null, color text not null, nib_size text not null, nib_type text not null, archived boolean not null default false, favorite boolean not null default false, needs_refill boolean not null default false,
 version bigint not null default 1 check (version > 0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.inks (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 brand text not null, collection text not null default '', name text not null, color_hex text check (color_hex ~ '^#[0-9A-Fa-f]{6}$'), archived boolean not null default false, favorite boolean not null default false, check (id <> 'NONE'),
 version bigint not null default 1 check (version > 0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.refill_events (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 pen_id text not null, occurred_on date not null, kind text not null check (kind in ('refill','cleaning')), notes text not null default '', not_pure boolean not null default false, sequence bigint generated by default as identity unique check (sequence > 0), foreign key (owner_id,pen_id) references public.pens(owner_id,id) on delete restrict, check (kind <> 'cleaning' or not not_pure),
 version bigint not null default 1 check (version > 0),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.refill_event_inks (
 owner_id uuid not null,
 event_id text not null,
 ink_id text not null,
 position integer not null check (position >= 0),
 primary key (event_id,ink_id), unique (event_id,position),
 foreign key (owner_id,event_id) references public.refill_events(owner_id,id) on delete cascade,
 foreign key (owner_id,ink_id) references public.inks(owner_id,id) on delete restrict
);
create index refill_pen_history on public.refill_events(owner_id,pen_id,occurred_on desc,sequence desc);
create index refill_journal on public.refill_events(owner_id,occurred_on desc,sequence desc);
create index refill_ink_history on public.refill_event_inks(owner_id,ink_id,event_id);

revoke all on private.collection_owner, private.data_imports, private.mutation_receipts from public,anon,authenticated;
revoke all on sequence public.refill_events_sequence_seq from public,anon,authenticated;

-- This role can read the allowlist but cannot change it; the helper returns only membership.
grant select on private.collection_owner to collection_writer;
create function private.is_owner() returns boolean language sql stable security definer set search_path = '' as $$
 select exists(select 1 from private.collection_owner where user_id = (select auth.uid()))
$$;
alter function private.is_owner() owner to collection_writer;
revoke all on function private.is_owner() from public, anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_owner() to authenticated;
alter table public.pens enable row level security;
alter table public.pens force row level security;
revoke all on public.pens from public, anon, authenticated;
grant select on public.pens to authenticated, collection_writer;
create policy owner_read on public.pens for select to authenticated, collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()));
alter table public.inks enable row level security;
alter table public.inks force row level security;
revoke all on public.inks from public, anon, authenticated;
grant select on public.inks to authenticated, collection_writer;
create policy owner_read on public.inks for select to authenticated, collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()));
alter table public.refill_events enable row level security;
alter table public.refill_events force row level security;
revoke all on public.refill_events from public, anon, authenticated;
grant select on public.refill_events to authenticated, collection_writer;
create policy owner_read on public.refill_events for select to authenticated, collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()));
alter table public.refill_event_inks enable row level security;
alter table public.refill_event_inks force row level security;
revoke all on public.refill_event_inks from public, anon, authenticated;
grant select on public.refill_event_inks to authenticated, collection_writer;
create policy owner_read on public.refill_event_inks for select to authenticated, collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()));
-- Only queue mutation is exposed in this slice. Future commands must grant only required DML.
grant update (needs_refill,version,updated_at) on public.pens to collection_writer;
create policy owner_queue on public.pens for update to collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()))
 with check (owner_id = (select auth.uid()) and (select private.is_owner()));
alter table private.collection_owner enable row level security;
create policy writer_owner_lookup on private.collection_owner for select to collection_writer using (true);
alter table private.data_imports enable row level security;
alter table private.mutation_receipts enable row level security;
grant select, insert on private.mutation_receipts to collection_writer;
create policy writer_receipts on private.mutation_receipts for all to collection_writer
 using (owner_id = (select auth.uid()) and (select private.is_owner()))
 with check (owner_id = (select auth.uid()) and (select private.is_owner()));

-- Deferred cross-table invariant, including old parent when a privileged link moves.
create function private.check_event_links() returns trigger language plpgsql set search_path = '' as $$
declare target text; targets text[]; event_kind text; n bigint; low integer; high integer;
begin
 if tg_table_name = 'refill_events' then
  if tg_op <> 'DELETE' then targets := array[new.id]; end if;
 else
  if tg_op <> 'INSERT' then targets := array[old.event_id]; end if;
  if tg_op <> 'DELETE' then targets := array_append(targets,new.event_id); end if;
 end if;
 foreach target in array coalesce(targets,array[]::text[]) loop
  select kind into event_kind from public.refill_events where id=target;
  if not found then continue; end if;
  select count(*),min(position),max(position) into n,low,high from public.refill_event_inks where event_id=target;
  if (event_kind='cleaning' and n<>0) or
     (event_kind='refill' and (n=0 or low<>0 or high<>n-1)) then
   raise exception 'invalid event links' using errcode='23514';
  end if;
 end loop;
 return null;
end $$;
revoke all on function private.check_event_links() from public, anon, authenticated;
create constraint trigger event_links_valid after insert or update or delete on public.refill_events
 deferrable initially deferred for each row execute function private.check_event_links();
create constraint trigger event_links_valid after insert or update or delete on public.refill_event_inks
 deferrable initially deferred for each row execute function private.check_event_links();

-- Canonical digest is SHA256 of UTF8 PostgreSQL jsonb::text for this versioned command.
-- All commands and imports share advisory lock (17012026,1), acquired before row reads.
create function private.set_pen_queue(p_request_id uuid, p_pen_id text, p_expected_version bigint, p_needs_refill boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_owner uuid := auth.uid(); v_hash text; receipt private.mutation_receipts; pen public.pens; answer jsonb;
begin
 if v_owner is null or not private.is_owner() then raise exception 'forbidden' using errcode='42501'; end if;
 if p_request_id is null or p_pen_id is null or p_pen_id='' or p_expected_version is null or p_expected_version<1 or p_needs_refill is null then
  raise exception 'validation' using errcode='22023';
 end if;
 perform pg_catalog.pg_advisory_xact_lock(17012026,1);
 v_hash := encode(sha256(convert_to(jsonb_build_array('set_pen_queue/v1',p_pen_id,p_expected_version::text,p_needs_refill)::text,'UTF8')),'hex');
 select * into receipt from private.mutation_receipts where owner_id=v_owner and request_id=p_request_id;
 if found then
  if receipt.command<>'set_pen_queue/v1' or receipt.payload_sha256<>v_hash then raise exception 'request conflict' using errcode='40001'; end if;
  return receipt.result;
 end if;
 select * into pen from public.pens where id=p_pen_id and owner_id=v_owner for update;
 if not found then raise exception 'not found' using errcode='P0002'; end if;
 if pen.version<>p_expected_version then raise exception 'version conflict' using errcode='40001'; end if;
 -- A semantic no-op keeps the version, while still recording a durable retry receipt.
 if pen.needs_refill<>p_needs_refill then
  update public.pens set needs_refill=p_needs_refill,version=version+1,updated_at=now()
   where id=p_pen_id and owner_id=v_owner returning * into pen;
 end if;
 answer := jsonb_build_object('id',pen.id,'version',pen.version::text,'needsRefill',pen.needs_refill);
 insert into private.mutation_receipts(owner_id,request_id,command,payload_sha256,result)
 values(v_owner,p_request_id,'set_pen_queue/v1',v_hash,answer);
 return answer;
end $$;
alter function private.set_pen_queue(uuid,text,bigint,boolean) owner to collection_writer;
revoke all on function private.set_pen_queue(uuid,text,bigint,boolean) from public,anon,authenticated;
grant execute on function private.set_pen_queue(uuid,text,bigint,boolean) to authenticated;
create function public.set_pen_queue(p_request_id uuid,p_pen_id text,p_expected_version bigint,p_needs_refill boolean)
returns jsonb language sql security invoker set search_path = '' as $$
 select private.set_pen_queue(p_request_id,p_pen_id,p_expected_version,p_needs_refill)
$$;
revoke all on function public.set_pen_queue(uuid,text,bigint,boolean) from public,anon,authenticated;
grant execute on function public.set_pen_queue(uuid,text,bigint,boolean) to authenticated;
