-- Local review candidate. No owner, Auth user, Storage bucket, or production data is provisioned.
create schema private;
revoke all on schema private from public, anon, authenticated;
revoke create on schema public from public, anon, authenticated;
alter default privileges in schema public revoke execute on functions from public;
alter default privileges in schema private revoke execute on functions from public;

create table private.collection_owner (
 singleton boolean primary key default true check (singleton),
 user_id uuid not null unique references auth.users(id) on delete restrict,
 time_zone text not null check (time_zone = 'America/Chicago')
);
create table private.data_imports (
 id text primary key check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id),
 source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
 mapping_version text not null,
 manifest jsonb not null check (jsonb_typeof(manifest) = 'object'),
 imported_at timestamptz not null default now()
);
create table public.pens (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 brand text not null, model text not null, color text not null, nib_size text not null, nib_type text not null, archived boolean not null default false, favorite boolean not null default false, needs_refill boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.inks (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 brand text not null, collection text not null default '', name text not null, color_hex text check (color_hex ~ '^#[0-9A-Fa-f]{6}$'), archived boolean not null default false, favorite boolean not null default false, check (id <> 'NONE'),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.refill_events (
 id text primary key default gen_random_uuid()::text check (id <> ''),
 owner_id uuid not null references private.collection_owner(user_id) on delete restrict,
 pen_id text not null, occurred_on date not null, kind text not null check (kind in ('refill','cleaning')), notes text not null default '', not_pure boolean not null default false, sequence bigint generated by default as identity unique check (sequence > 0), foreign key (owner_id,pen_id) references public.pens(owner_id,id) on delete restrict, check (kind <> 'cleaning' or not not_pure),
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique (owner_id, id)
);
create table public.refill_event_inks (
 owner_id uuid not null,
 event_id text not null,
 ink_id text not null,
 position integer not null check (position >= 0),
 primary key (event_id,ink_id), unique (event_id,position),
 foreign key (owner_id,event_id) references public.refill_events(owner_id,id) on delete cascade,
 foreign key (owner_id,ink_id) references public.inks(owner_id,id) on delete restrict
);
create index refill_pen_history on public.refill_events(owner_id,pen_id,occurred_on desc,sequence desc);
create index refill_journal on public.refill_events(owner_id,occurred_on desc,sequence desc);
create index refill_ink_history on public.refill_event_inks(owner_id,ink_id,event_id);

-- Standard authenticated DML is restricted to the configured owner by RLS.
-- The only definer helper reads the private allowlist and returns a boolean.
-- It is owned by the migration operator; no custom role or delegated auth grant.
revoke all on private.collection_owner,private.data_imports from public,anon,authenticated;
alter table private.collection_owner enable row level security;
alter table private.data_imports enable row level security;
create function private.is_owner() returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from private.collection_owner where user_id=(select auth.uid()))
$$;
revoke all on function private.is_owner() from public,anon,authenticated;
grant usage on schema private to authenticated;
grant execute on function private.is_owner() to authenticated;
alter table public.pens enable row level security;
alter table public.pens force row level security;
revoke all on public.pens from public,anon,authenticated;
grant select,insert,update,delete on public.pens to authenticated;
create policy owner_write on public.pens for all to authenticated
 using (owner_id=(select auth.uid()) and (select private.is_owner()))
 with check (owner_id=(select auth.uid()) and (select private.is_owner()));
alter table public.inks enable row level security;
alter table public.inks force row level security;
revoke all on public.inks from public,anon,authenticated;
grant select,insert,update,delete on public.inks to authenticated;
create policy owner_write on public.inks for all to authenticated
 using (owner_id=(select auth.uid()) and (select private.is_owner()))
 with check (owner_id=(select auth.uid()) and (select private.is_owner()));
alter table public.refill_events enable row level security;
alter table public.refill_events force row level security;
revoke all on public.refill_events from public,anon,authenticated;
grant select,insert,update,delete on public.refill_events to authenticated;
create policy owner_write on public.refill_events for all to authenticated
 using (owner_id=(select auth.uid()) and (select private.is_owner()))
 with check (owner_id=(select auth.uid()) and (select private.is_owner()));
alter table public.refill_event_inks enable row level security;
alter table public.refill_event_inks force row level security;
revoke all on public.refill_event_inks from public,anon,authenticated;
grant select,insert,update,delete on public.refill_event_inks to authenticated;
create policy owner_write on public.refill_event_inks for all to authenticated
 using (owner_id=(select auth.uid()) and (select private.is_owner()))
 with check (owner_id=(select auth.uid()) and (select private.is_owner()));
revoke all on sequence public.refill_events_sequence_seq from public,anon,authenticated;
grant usage on sequence public.refill_events_sequence_seq to authenticated;

-- Deferred cross-table invariant, including old parent when a privileged link moves.
create function private.check_event_links() returns trigger language plpgsql set search_path = '' as $$
declare target text; targets text[]; event_kind text; n bigint; low integer; high integer;
begin
 if tg_table_name = 'refill_events' then
  if tg_op <> 'DELETE' then targets := array[new.id]; end if;
 else
  if tg_op <> 'INSERT' then targets := array[old.event_id]; end if;
  if tg_op <> 'DELETE' then targets := array_append(targets,new.event_id); end if;
 end if;
 foreach target in array coalesce(targets,array[]::text[]) loop
  select kind into event_kind from public.refill_events where id=target;
  if not found then continue; end if;
  select count(*),min(position),max(position) into n,low,high from public.refill_event_inks where event_id=target;
  if (event_kind='cleaning' and n<>0) or
     (event_kind='refill' and (n=0 or low<>0 or high<>n-1)) then
   raise exception 'invalid event links' using errcode='23514';
  end if;
 end loop;
 return null;
end $$;
revoke all on function private.check_event_links() from public, anon, authenticated;
create constraint trigger event_links_valid after insert or update or delete on public.refill_events
 deferrable initially deferred for each row execute function private.check_event_links();
create constraint trigger event_links_valid after insert or update or delete on public.refill_event_inks
 deferrable initially deferred for each row execute function private.check_event_links();
